const express = require("express")
const router = express.Router()
const userController = require('../app/controllers/userController')
const adminController = require("../app/controllers/adminController")
const authenticate = require("../app/middlewares/authenticate")
const uploadAccountFiles = require("../app/middlewares/uploadFiles/uploadAccountFiles")
const authorizeUser = require("../app/middlewares/authorization")

// router.get("/users",userController.list)
router.post('/user/register',userController.register)
router.post('/user/login',userController.login)
router.post('/user/forgot-password',userController.sendForgotPasswordLink)
router.post('/user/change-password/:token',userController.changePassword)
router.post('/user/account', authenticate, uploadAccountFiles, userController.addUserProfile)
router.get('/user/account', authenticate, userController.getUserAccount)
// router.get("/user/courses",authenticate,userController.getAllCourses)
router.get("/allcourses",userController.getAllCourses)
///////////////////////
router.post('/admin/login',adminController.login)
router.post("/admin/courses",authenticate,authorizeUser(["admin"]),adminController.addCourse),
router.get("/admin/mycourses",authenticate,adminController.getMyCourses)
router.get("/admin/users",authenticate,authorizeUser(["admin"]),adminController.getAllUsers)
router.post("/admin/course/:courseId/lecture",authenticate,authorizeUser(["admin"]), adminController.addLecture)
router.get("/admin/course/:courseId/lectures",authenticate,authorizeUser(["admin","user"]), adminController.getLectures)
router.delete("/admin/user/:userId",authenticate,authorizeUser(["admin"]),adminController.deleteUser)
router.delete("/admin/course/:courseId",authenticate,authorizeUser(["admin"]),adminController.deleteCourse)
router.delete("/admin/user/profile/:userId",authenticate,authorizeUser(["admin"]),adminController.deleteUserProfile)
module.exports=router